### ISSUE TITLE
Will this DDI manage DHCP server as well?

### ISSUE THREAD

**Issue by Blason** [TeemIp/teemip-ip-request-mgmt#2]
Hi Team,

I am planning to use DDI standalone module in home network and instead of DNS; I would want to use DHCP and IPAM only. I want to know if I can manage DHCP scope and DHCP related options with TeeemIP or this is just to maintain the inventory of DHCP server and options related to DHCP?

**Comment by Hipska** [comment]
By default there is only inventory. But we as a partner did an integration with Microsoft DHCP server and Infoblox in the past.

**Comment by Blason** [comment]
Can that work with Linux DHCP? Would you mind any sharing any references?

**Comment by Hipska** [comment]
A similar integration needs to be done, so complete new implementation. Basically you need too get familiar with the API of iTop/TeemIP and Linux DHCP and manage its configuration.
