### ISSUE TITLE
Can't create IP request

### ISSUE THREAD

**Issue by minhquan231** [TeemIp/teemip-ip-request-mgmt#3]
When I create a tick , I received information about this problem. I using PHP 8.3, teemip version 3.2. 
Error: Event 'EVENT_DB_BEFORE_WRITE' for 'OnBeforeWriteTicket'} failed with non-blocking error: Unknown attribute functionalcis_list from class IPRequestAddressDelete.
![image](https://github.com/user-attachments/assets/63a243d7-29f7-42ef-9d1d-90e61da5f13c)

**Comment by xtophe38** [comment]
Thanks for the hint. The question is: "why functionalcis_list" not an attribute of the Ticket branch anymore. I'm digging into it.

**Comment by xtophe38** [comment]
OK. This only concerns the standalone product. The IPAM for iTop extension used with iTop is not touched.

It looks like some reassignment of attribute definitions have been done between itop-ticket and itop-bridge-cmdb-ticket ! Consequence for the standalone product is that the Ticket class has attribuet functionalcis_list which relies on the lnkFunctionaCIToTicket class while this class is defined... in the itop-bridge-cmdb-ticket that is not inlcuded in TeemIp standalone !

Resolution consists in adding the bridge extension in the datamodels/2.x/ directory and modifying the installation.xml file to make sure it is loaded. This will be corrected in TeemIp 3.2.1.

**Comment by xtophe38** [comment]
Corrected: the itop-bridge-cmdb-ticket extension is now part of version 3.2.1-2412 of TeemIp standalone.
